# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title:  Elon Chung
subtitle:
description:
author: Elon Chung
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.elonchung.cn
root: /
#permalink: :year/:month/:day/:title/
permalink: :year/:month/:title/
permalink_defaults: 

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: pure

# Deployment
## Docs: https://hexo.io/docs/deployment.html
#deploy:
#   type: git
#   repo: git@github.com:zhongweixiang/zhongweixiang.github.io.git
#   branch: master
deploy:
  - type: git
    repository:  git@github.com:zhongweixiang/zhongweixiang.github.io.git
    branch: master
  - type: baidu_url_submitter

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

algolia:
  applicationID: 'Y41MM64BIR'
  apiKey: '53e07de8471cdf21a4275b04800b8f59'
  adminApiKey: '48250562a0ce2d550fde96a3193ffedb'
  indexName: 'hexo'
  chunkSize: 5000 

#jsonContent:
#    meta: false
#    pages: false
#    posts:
#      title: true
#      date: true
#      path: true
#      text: false
#      raw: false
#      content: false
#      slug: false
#      updated: false
#      comments: false
#      link: false
#      permalink: false
#      excerpt: false
#      categories: false
#      tags: true

# pure主题使用的插件
jsonContent:
  ignore:
    - path/to/a/page
    - url/to/one/post
    - an-entire-category
    - specific.file
    - .ext # a file extension

baidu_url_submit:
  count: 3 ## 提交最新的一个链接
  host: www.elonchung.cn ## 在百度站长平台中注册的域名
  token: u6Retu80nmbwbeLX ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里

# 自动压缩html、css、js代码
neat_enable: true

#压缩html代码
neat_html:
  enable: true
  exclude:

#压缩CSS
neat_css:
  enable: true
  exclude:
    - '*.min.css'
#压缩JS    
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'


#RESTful JSON数据生成插件。
restful:
  # site 可配置为数组选择性生成某些属性
  # site: ['title', 'subtitle', 'description', 'author', 'since', email', 'favicon', 'avatar']
  site: true        # hexo.config mix theme.config
  posts_size: 10    # 文章列表分页，0 表示不分页
  posts_props:      # 文章列表项的需要生成的属性
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    excerpt: false
    cover: true      # 封面图，取文章第一张图片
    content: false
    keywords: false
    categories: true
    tags: true
  categories: true  # 分类数据
  tags: true        # 标签数据
  post: true        # 文章数据
  pages: false      # 额外的 Hexo 页面数据, 如 About




sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
